name: Aula Pratica 5 CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up environment
      shell: bash
      run: |
        if [[ $RUNNER_OS == "Linux" ]]; then
          sudo apt-get update
          sudo apt-get install g++ -y
        elif [[ $RUNNER_OS == "macOS" ]]; then
          brew install gcc
        elif [[ $RUNNER_OS == "Windows" ]]; then
          choco install mingw
        fi

    - name: Compile and Run Tests
      shell: bash
      run: |
        if [[ $RUNNER_OS == "Windows" ]]; then
          g++ NumberList.cpp NumberListTest.cpp -o NumberListTest.exe
          ./NumberListTest.exe
        else
          g++ NumberList.cpp NumberListTest.cpp -o NumberListTest
          ./NumberListTest
        fi